apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: dp-pdl-cache
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: {{ image }}
  port: 8080

  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}

  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true

  tokenx:
    enabled: true

  valkey:
    - instance: identer
      access: readwrite

  env:
    - name: PDL_API_HOST
      value: {{ PDL_API_HOST }}
    - name: PDL_AUDIENCE
      value: {{ PDL_AUDIENCE }}
    - name: JDK_JAVA_OPTIONS # Bytter GC og lar JVMen se at det er flere CPU kjerner
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4

  accessPolicy:
    outbound:
      external:
        - host: {{ PDL_API_HOST }}
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp


