apiVersion: aiven.io/v1alpha1
kind: Valkey

metadata:
  labels:
    app: dp-pdl-cache
    namespace: teamdagpenger
  name: valkey-teamdagpenger-identer
  namespace: teamdagpenger
spec:
  plan: {{ valkey.plan }}
  project: {{ valkey.project }}
